# Generated by Django 5.0.6 on 2024-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subplan_highlight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeature',
            name='Subplan',
        ),
        migrations.AddField(
            model_name='subplanfeature',
            name='Subplan',
            field=models.ManyToManyField(to='main.subplan'),
        ),
    ]
