# Generated by Django 5.0.6 on 2024-07-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_subplan_validity_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
